export const genreList = [
    "Fantasy Writer",
    "Historical Fiction",
    "Sci-Fi Writer",
    "Romance Writer",
    "Dystopian Writer",
    "Mystery Writer",
    "Poetry Writer",
    "Science Fiction Writer",
    "Paranormal Writer",
    "Suspense Writer",
    "Thriller Writer",
    "Fiction Writer",
    "Horror Writer",
];