import React from 'react'

const randomNumberInRange = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min

const Stories = [
    {
      title: "The Enchanted Forest",
      href: `/${1}`,
      cover: "/placeholder.svg",
      author: "John Doe",
      Typerole: "Fantasy Writer",
      date: "2024-07-01",
      scribe: "Embark on a magical journey through the Enchanted Forest, where wonder and adventure await.",
    },
    {
      title: "The Forgotten Empire",
      href: `/${2}`,
      cover: "/placeholder.svg",
      author: "Jane Smith",
      Typerole: "Historical Fiction",
      date: "2024-07-02",
      scribe: "Uncover the secrets of a long-lost civilization in this captivating historical tale.",
    },
    {
      title: "Interstellar Odyssey",
      href: `/${3}`,
      cover: "/placeholder.svg",
      author: "Michael Johnson",
      Typerole: "Sci-Fi Writer",
      date: "2024-07-03",
      scribe: "Embark on a thrilling journey through the vast expanse of space in this captivating sci-fi tale.",
    },
    {
      title: "Love's Eternal Embrace",
      href: `/${4}`,
      cover: "/placeholder.svg",
      author: "Emily Davis",
      Typerole: "Romance Writer",
      date: "2024-07-04",
      scribe: "Lose yourself in a captivating tale of timeless love and passion.",
    },
    {
      title: "The Crimson Enigma",
      href: `/${5}`,
      cover: "/placeholder.svg",
      author: "David Lee",
      Typerole: "Mystery Novelist",
      date: "2024-07-05",
      scribe: "Unravel the threads of a captivating mystery in this thrilling page-turner.",
    },
    {
      title: "The Dreamers' Awakening",
      href: `/${6}`,
      cover: "/placeholder.svg",
      author: "Sarah Kim",
      Typerole: "Young Adult Author",
      date: "2024-07-06",
      scribe: "Discover the power of dreams and the courage to face the unknown.",
    },
    {
      title: "Whispers in the Dark",
      href: `/${7}`,
      cover: "/placeholder.svg",
      author: "Alex Chen",
      Typerole: "Horror Storyteller",
      date: "2024-07-07",
      scribe: "Brace yourself for a chilling tale that will haunt your dreams.",
    },
    {
      title: "The Enchanted Tapestry",
      href: `/${8}`,
      cover: "/placeholder.svg",
      author: "Olivia Nguyen",
      Typerole: "Magical Realism",
      date: "2024-07-08",
      scribe: "Discover the magic that lies within the threads of a captivating tapestry.",
    },
    {
      title: "The Forgotten Kingdom",
      href: `/${9}`,
      cover: "/placeholder.svg",
      author: "Ethan Gonzalez",
      Typerole: "Historical Fantasy",
      date: "2024-07-09",
      scribe: "Uncover the secrets of a long-lost kingdom and the extraordinary tales that lie within.",
    },
    {
      title: "The Hidden World",
      href: `/${10}`,
      cover: "/placeholder.svg",
      author: "Sophia Chen",
      Typerole: "Science Fiction Writer",
      date: "2024-07-10",
      scribe: "Embark on an epic adventure through the vast expanse of hidden worlds.",
    },
    ...Array.from({ length: 20 }, (_, i) => ({
      title: "The Hidden Kingdom",
      href: `/${11 + i}`,
      cover: "/placeholder.svg",
      author: `Daniel Lee${randomNumberInRange(1, 10000)}`,
      Typerole: "Science Fiction Writer",
      date: `2024-07-${11 + i}`,
      scribe: "Embark on an epic adventure through the vast expanse of hidden worlds.",
    })),
  ];

export default Stories;
